package api

import("net/http";"net/mail";"net";"strings";"time";"github.com/jackc/pgx/v5/pgconn";"errors";"context";"pulseroute/internal/redisx";"pulseroute/internal/security")

type credentials struct{Email string `json:"email"`;Password string `json:"password"`}
func(s *Server)authLimit(w http.ResponseWriter,r *http.Request)bool{ip,_,_:=net.SplitHostPort(r.RemoteAddr);ok,e:=redisx.Allow(r.Context(),s.Redis,"auth:"+ip,1,10);if e!=nil{fail(w,r,503,"UNAVAILABLE","authentication temporarily unavailable");return false};if !ok{w.Header().Set("Retry-After","1");fail(w,r,429,"RATE_LIMITED","try again shortly");return false};return true}
func(s *Server)register(w http.ResponseWriter,r *http.Request){if !s.authLimit(w,r){return};var c credentials;if !decode(w,r,&c){return};c.Email=strings.ToLower(strings.TrimSpace(c.Email));a,e:=mail.ParseAddress(c.Email);if e!=nil||a.Address!=c.Email||len(c.Email)>254{fail(w,r,400,"INVALID_EMAIL","a valid email is required");return};hash,e:=security.Password(c.Password);if e!=nil{fail(w,r,400,"INVALID_PASSWORD",e.Error());return};id:=security.Token("usr_");_,e=s.DB.Exec(r.Context(),"INSERT INTO users(id,email,password_hash) VALUES($1,$2,$3)",id,c.Email,hash);if e!=nil{var pe *pgconn.PgError;if errors.As(e,&pe)&&pe.Code=="23505"{fail(w,r,409,"CONFLICT","email already registered");return};s.dbError(w,r,e);return};s.session(w,r,id,201)}
func(s *Server)login(w http.ResponseWriter,r *http.Request){if !s.authLimit(w,r){return};var c credentials;if !decode(w,r,&c){return};var id,hash string;e:=s.DB.QueryRow(r.Context(),"SELECT id,password_hash FROM users WHERE email=$1",strings.ToLower(strings.TrimSpace(c.Email))).Scan(&id,&hash);if e!=nil||!security.CheckPassword(hash,c.Password){fail(w,r,401,"UNAUTHORIZED","invalid email or password");return};s.session(w,r,id,200)}
func(s *Server)session(w http.ResponseWriter,r *http.Request,id string,status int){token:=security.Token("ses_");_,e:=s.DB.Exec(r.Context(),"INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,$3)",security.Hash(token),id,time.Now().Add(24*time.Hour));if e!=nil{s.dbError(w,r,e);return};http.SetCookie(w,&http.Cookie{Name:"pulseroute_session",Value:token,Path:"/",HttpOnly:true,Secure:s.Config.CookieSecure,SameSite:http.SameSiteStrictMode,MaxAge:86400});write(w,status,map[string]string{"id":id})}
func(s *Server)auth(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){cookie,e:=r.Cookie("pulseroute_session");if e!=nil{fail(w,r,401,"UNAUTHORIZED","sign in required");return};var id string;e=s.DB.QueryRow(r.Context(),"SELECT user_id FROM sessions WHERE token_hash=$1 AND expires_at>now()",security.Hash(cookie.Value)).Scan(&id);if e!=nil{fail(w,r,401,"UNAUTHORIZED","session expired or invalid");return};next.ServeHTTP(w,r.WithContext(context.WithValue(r.Context(),userKey,id)))})}
func(s *Server)logout(w http.ResponseWriter,r *http.Request){c,_:=r.Cookie("pulseroute_session");if _,e:=s.DB.Exec(r.Context(),"DELETE FROM sessions WHERE token_hash=$1",security.Hash(c.Value));e!=nil{s.dbError(w,r,e);return};http.SetCookie(w,&http.Cookie{Name:"pulseroute_session",Value:"",Path:"/",HttpOnly:true,Secure:s.Config.CookieSecure,SameSite:http.SameSiteStrictMode,MaxAge:-1});w.WriteHeader(204)}
