package api
import("net/http";"time";"fmt";"encoding/json";"pulseroute/internal/redisx")
func filters(r *http.Request)(string,string,string,string){q:=r.URL.Query();return q.Get("project_id"),q.Get("status"),q.Get("type"),q.Get("endpoint_id")}
func since(r *http.Request)(time.Time,error){if v:=r.URL.Query().Get("since");v!=""{t,e:=time.Parse(time.RFC3339,v);if e!=nil{return t,fmt.Errorf("since must be RFC3339")};return t,nil};return time.Date(1970,1,1,0,0,0,0,time.UTC),nil}
func(s *Server)events(w http.ResponseWriter,r *http.Request){p,_,t,_:=filters(r);start,e:=since(r);if e!=nil{fail(w,r,400,"INVALID_DATE",e.Error());return};l,o:=page(r);s.rows(w,r,`SELECT e.id,e.project_id,e.event_id,e.type,e.created_at FROM events e JOIN projects p ON p.id=e.project_id WHERE p.owner_id=$1 AND ($2='' OR p.id=$2) AND ($3='' OR e.type=$3) AND e.created_at>=$4 ORDER BY e.created_at DESC,e.id LIMIT $5 OFFSET $6`,user(r),p,t,start,l,o)}
func(s *Server)event(w http.ResponseWriter,r *http.Request){s.one(w,r,`SELECT json_build_object('id',e.id,'project_id',e.project_id,'event_id',e.event_id,'type',e.type,'payload',e.payload,'created_at',e.created_at,'deliveries',COALESCE((SELECT json_agg(json_build_object('id',d.id,'endpoint_id',d.endpoint_id,'status',d.status,'attempt_count',d.attempt_count)) FROM deliveries d WHERE d.event_id=e.id),'[]'::json)) FROM events e JOIN projects p ON p.id=e.project_id WHERE e.id=$1 AND p.owner_id=$2`,r.PathValue("id"),user(r))}
func(s *Server)deliveries(w http.ResponseWriter,r *http.Request){s.deliveryList(w,r,false)}
func(s *Server)deadLetters(w http.ResponseWriter,r *http.Request){s.deliveryList(w,r,true)}
func(s *Server)deliveryList(w http.ResponseWriter,r *http.Request,dead bool){p,status,t,endpoint:=filters(r);if dead{status="dead"};start,e:=since(r);if e!=nil{fail(w,r,400,"INVALID_DATE",e.Error());return};l,o:=page(r);s.rows(w,r,`SELECT d.id,d.event_id,e.event_id AS external_event_id,e.type,e.project_id,d.endpoint_id,ep.name AS endpoint_name,d.status,d.attempt_count,d.generation,d.next_attempt_at,d.created_at,dl.reason FROM deliveries d JOIN events e ON e.id=d.event_id JOIN projects p ON p.id=e.project_id JOIN endpoints ep ON ep.id=d.endpoint_id LEFT JOIN dead_letters dl ON dl.delivery_id=d.id WHERE p.owner_id=$1 AND ($2='' OR p.id=$2) AND ($3='' OR d.status=$3) AND ($4='' OR e.type=$4) AND ($5='' OR ep.id=$5) AND d.created_at>=$6 ORDER BY d.created_at DESC,d.id LIMIT $7 OFFSET $8`,user(r),p,status,t,endpoint,start,l,o)}
func(s *Server)delivery(w http.ResponseWriter,r *http.Request){s.one(w,r,`SELECT json_build_object('id',d.id,'event_id',d.event_id,'endpoint_id',d.endpoint_id,'endpoint_name',ep.name,'status',d.status,'attempt_count',d.attempt_count,'generation',d.generation,'next_attempt_at',d.next_attempt_at,'created_at',d.created_at,'attempts',COALESCE((SELECT json_agg(a ORDER BY a.generation,a.attempt) FROM delivery_attempts a WHERE a.delivery_id=d.id),'[]'::json)) FROM deliveries d JOIN events e ON e.id=d.event_id JOIN projects p ON p.id=e.project_id JOIN endpoints ep ON ep.id=d.endpoint_id WHERE d.id=$1 AND p.owner_id=$2`,r.PathValue("id"),user(r))}
func(s *Server)replay(w http.ResponseWriter,r *http.Request){tx,e:=s.DB.Begin(r.Context());if e!=nil{s.dbError(w,r,e);return};defer tx.Rollback(r.Context());var status string;var active bool;e=tx.QueryRow(r.Context(),`SELECT d.status,ep.active AND ep.deleted_at IS NULL FROM deliveries d JOIN events e ON e.id=d.event_id JOIN projects p ON p.id=e.project_id JOIN endpoints ep ON ep.id=d.endpoint_id WHERE d.id=$1 AND p.owner_id=$2 FOR UPDATE OF d`,r.PathValue("id"),user(r)).Scan(&status,&active);if e!=nil{s.dbError(w,r,e);return};if status!="dead"||!active{fail(w,r,409,"REPLAY_CONFLICT","only dead deliveries with an active endpoint can be replayed");return};_,e=tx.Exec(r.Context(),"UPDATE deliveries SET status='pending',attempt_count=0,generation=generation+1,next_attempt_at=now(),lease_until=NULL,lease_token=NULL,updated_at=now() WHERE id=$1",r.PathValue("id"));if e==nil{_,e=tx.Exec(r.Context(),"DELETE FROM dead_letters WHERE delivery_id=$1",r.PathValue("id"))};if e==nil{e=tx.Commit(r.Context())};if e!=nil{s.dbError(w,r,e);return};write(w,202,map[string]string{"id":r.PathValue("id"),"status":"pending"})}
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){p:=r.URL.Query().Get("project_id");key:="dashboard:"+user(r)+":"+p;var result json.RawMessage;if redisx.Cached(r.Context(),s.Redis,key,&result){write(w,200,result);return};var b []byte;e:=s.DB.QueryRow(r.Context(),`WITH owned AS (SELECT id FROM projects WHERE owner_id=$1 AND ($2='' OR id=$2)), ev AS (SELECT e.* FROM events e JOIN owned p ON p.id=e.project_id), ds AS (SELECT d.* FROM deliveries d JOIN ev e ON e.id=d.event_id), attempts AS (SELECT a.* FROM delivery_attempts a JOIN ds d ON d.id=a.delivery_id) SELECT json_build_object('events_received',(SELECT count(*) FROM ev),'events_today',(SELECT count(*) FROM ev WHERE created_at>=date_trunc('day',now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'),'deliveries_attempted',(SELECT count(*) FROM attempts),'succeeded',(SELECT count(*) FROM ds WHERE status='succeeded'),'failed',(SELECT count(*) FROM attempts WHERE status_code<200 OR status_code>=300),'retrying',(SELECT count(*) FROM ds WHERE status='retrying'),'dead',(SELECT count(*) FROM ds WHERE status='dead'),'pending',(SELECT count(*) FROM ds WHERE status IN ('pending','processing')),'success_rate',(SELECT COALESCE(100.0*count(*) FILTER(WHERE status='succeeded')/NULLIF(count(*) FILTER(WHERE status IN ('succeeded','dead')),0),0) FROM ds),'average_latency_ms',(SELECT COALESCE(avg(duration_ms),0) FROM attempts),'cache_ttl_seconds',5)`,user(r),p).Scan(&b);if e!=nil{s.dbError(w,r,e);return};result=b;redisx.Cache(r.Context(),s.Redis,key,result);write(w,200,result)}
